apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ralph-resume
  name: ralph-resume
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: ralph-resume
status:
  loadBalancer: {}
